query onePays($id: ID!) {
   pay(id: $id) {
     id
     Nom
     carte
     articles (sort: "dateDePublication:desc") {
       id
       titre
       dateDePublication
       imagePresentation {
         url
       }
       contenu
     }
     recettes {
       id
       titre
       recette
       photo {
          url
       }
     }
     rencontres {
       id
       nom
       texte
       photo {
         id
         url
       }
     }
     galerie {
       id
       photos {
         id
         url
       }
     }
   }
 }


